export type instead of export
Hi
I am trying to use Your library with isolatedModules in my tsconfig an this gives me an warning:

```
node_modules/vue-markdown-render/src/VueMarkdown.ts:3:10 - error TS1205: Re-exporting a type when 'isolatedModules' is enabled requires using 'export type'.

export { Options } from 'markdown-it'
              ~~~~~~~
```
i think it should be 
```
export type { Options } from 'markdown-it'
```
To provide more compatibility.